language: python
sudo: true

matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.5"


install:
  # Note we disable progress bars to make Travis log loading much faster

  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install -q -c conda-forge pytest dask distributed
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then  # Taken from https://github.com/blei-lab/edward/blob/master/.travis.yml
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0rc0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0rc0-cp34-cp34m-linux_x86_64.whl;
    fi
  - pip install -q git+https://github.com/dask/{dask,distributed}.git --upgrade

  # Install distributed
  - pip install --no-deps -e .

script:
    - py.test dask_tensorflow --verbose

notifications:
  email: false
